services:
  - type: web
    name: vacbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vacbot
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

databases:
  - name: vacbot
    plan: free